### ISSUE TITLE
agent-tags is not being displayed on agent matching view

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#829]
Agent-tags, despite correctly counting as matches, don't appear in agent matching view (check "tags" column)

![image](https://user-images.githubusercontent.com/78241475/152390428-d5b113e9-61da-40a5-956f-63495baf3e52.png)

![image](https://user-images.githubusercontent.com/78241475/152390721-825a267e-070e-4875-8796-ea5b4a165fce.png)

**Comment by manrodrigues** [comment]
Agent tags are not displayed on edit agents modal as well:

![image](https://user-images.githubusercontent.com/78241475/158183680-baabd8af-d3fe-45c6-a002-ffbc9bf95f38.png)

![image](https://user-images.githubusercontent.com/78241475/158183734-11c588fb-f3f7-4bed-96d1-257696dac982.png)

**Comment by manrodrigues** [comment]
@gpazuch  This is not working yet.. but I apologize because I guess the description is not enough helpful

The problem is the agent-tags (created using config files)

Look this agent:

![image](https://user-images.githubusercontent.com/78241475/165548112-a4f346f6-05ab-43d0-bf16-fcf5a48d4536.png)

He has `"orb_test": "tags"` as agent-tags and `"config_file": "agent"` as orb-tags

I provisioned the agent using this file:

[test_agent_name_Wch.zip](https://github.com/ns1labs/orb/files/8573168/test_agent_name_Wch.zip)

and edited the agent inserting the orb-tag through the UI.

When I open the matching agents view on groups page, I can only see the orb-tag:

![image](https://user-images.githubusercontent.com/78241475/165548839-7dfb4242-5f65-457d-a267-fd92d6d7f651.png)
 


Same thing happening on edit agent page:

![image](https://user-images.githubusercontent.com/78241475/165549000-a8d935da-d148-4d94-8c16-5978bb538931.png)

**Comment by gpazuch** [comment]
Fixed at some point in the past.
It is no longer happening.

**Comment by manrodrigues** [comment]
> @gpazuch This is not working yet.. but I apologize because I guess the description is not enough helpful
> 
> The problem is the agent-tags (created using config files)
> 
> Look this agent:
> 
> ![image](https://user-images.githubusercontent.com/78241475/165548112-a4f346f6-05ab-43d0-bf16-fcf5a48d4536.png)
> 
> He has `"orb_test": "tags"` as agent-tags and `"config_file": "agent"` as orb-tags
> 
> I provisioned the agent using this file:
> 
> [test_agent_name_Wch.zip](https://github.com/ns1labs/orb/files/8573168/test_agent_name_Wch.zip)
> 
> and edited the agent inserting the orb-tag through the UI.
> 
> When I open the matching agents view on groups page, I can only see the orb-tag:
> 
> ![image](https://user-images.githubusercontent.com/78241475/165548839-7dfb4242-5f65-457d-a267-fd92d6d7f651.png)
> 
> Same thing happening on edit agent page:
> 
> ![image](https://user-images.githubusercontent.com/78241475/165549000-a8d935da-d148-4d94-8c16-5978bb538931.png)

please note that it's NOT solved yet.. we are considering AGENT TAGS (only generated through config file)...

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/170593923-4a60a515-0f4b-4682-998b-34d8d69ba3bf.png)


is this closed perhaps?
@manrodrigues

**Comment by gpazuch** [comment]
@manrodrigues I believe I may have fixed this on last PR, with the modified agent.service.ts file.

**Comment by manrodrigues** [comment]
Sorry.. I had not seen your message.

This is related to AGENT TAGS (provisioned on agent config file)..

I have one tag from orb and one from the agent:


![image](https://user-images.githubusercontent.com/78241475/171672566-6645df8e-d520-4b8a-8b2d-94226e8a222f.png)

The group have both of them:

![image](https://user-images.githubusercontent.com/78241475/171672845-e9ed7193-3624-437f-a8cb-ded1d15827c2.png)

But on matching agents page, only the orb tag is being shown:

![image](https://user-images.githubusercontent.com/78241475/171673104-3e06fa56-ad98-4bbc-a1a8-acb2ffd1682c.png)

**Comment by manrodrigues** [comment]
ok :) 

![image](https://user-images.githubusercontent.com/78241475/171853697-20ee278e-c48d-441b-8870-55be93165f87.png)
